version: "3"
services:
    python:
        container_name: python
        build: ./docker/python
    plantuml-server:
        image: plantuml/plantuml-server
        restart: always
        ports:
            - "8080:8080"