@startuml Scraping

package スクレイピング集約 {
    object スクレイピング {
        URL
        HTML
        class名
        ホテル情報
    }
    object URL {
        ベースURL
        地域コード
        宿泊日
        料金上限
        ・・・
    }
    object 検索条件 {
        都道府県
        宿泊希望日
        料金上限
    }
    object 宿泊希望日 {
        年
        月
        日
    }
    object 料金 {
        最小料金
        最大料金
    }
}

note left of URL
    * 地域コードは必須
    * 宿泊希望日や料金条件が空だった場合は空欄を入力する
    * 検索条件の有無に関わらず、クエリパラメータはURLに含める
end note

note left of 検索条件
    * 都道府県は必須項目
end note

note left of 宿泊希望日
    * 必須でない
    * 日付は本日以降でなければならない
end note

note left of 料金
    * 必須でない
    * 最大料金 ≧ 最小料金でなければならない
    * 料金は正の整数でなければならない
endnote

スクレイピング "1" -down-* "1" URL
URL "1" -down-* "1" 検索条件
検索条件 "1" -down-* "1" 宿泊希望日
検索条件 "1" -down-* "1" 料金

package ホテル集約 {
    object ホテル {
        ホテル名
        住所
        ホテル画像
        プラン
    }
    object プラン {
        プラン名
        ホテル名
        料金
        チェックイン時間
        チェックアウト時間
    }
}

ホテル "1" -down-* "N" プラン
スクレイピング "1" -right-> "N" ホテル

@enduml